### ISSUE TITLE
multi-vterm-dedicated-open doesn't open to correct buffer

### ISSUE THREAD

**Issue by dylanjm** [suonlight/multi-vterm#10]
Ever since the update `multi-vterm-dedicated-open` will open a dedicated window but with the current buffer selected instead of the vterm-buffer.

Here is a short screen-cast to describe what I mean:

https://streamable.com/htstzv

**Comment by Ergus** [comment]
Same problem here. `multi-vterm-dedicated-open` created the term, splits the screen, but selects the same buffer where it was called.

**Comment by suonlight** [comment]
@dylanjm, @Ergus I have fixed it, pls give it a try

**Comment by dylanjm** [comment]
Works great thanks!
