### ISSUE TITLE
Now has hard dependency on projectile

### ISSUE THREAD

**Issue by articuluxe** [suonlight/multi-vterm#12]
How about using project.el instead?  Built in to emacs, can have projectile support added easily with a few lines.

**Comment by suonlight** [comment]
Thank @articuluxe, I'll think about it and try to remove projectile when I have time.

**Comment by titibandit** [comment]
Hey,
@articuluxe, you said that one can have projectile support in project.el by adding a few line. I'm not sure how I could go about that? 
I'm using projectile, and I can't use the function `multi-vterm-project` anymore, since it complains about the `project-root` variable being empty.

**Comment by articuluxe** [comment]
Hey,

Here is a simple one:

  ;; Bridge projectile and project together so packages that depend on project
  ;; like eglot work
  (defun my-projectile-project-find-function (dir)
    (let ((root (projectile-project-root dir)))
      (and root (cons 'transient root))))

  (projectile-mode t)

  (with-eval-after-load 'project
    (add-to-list 'project-find-functions 'my-projectile-project-find-function))


And here is a more complex one, that seems better, but I have not personally used it:


(defun m/projectile-project-find-function (dir)
  (let ((root (projectile-project-root dir)))
    (and root (cons 'my/projectile root))))

(cl-defmethod project-root ((pr (head my/projectile)))
  (cdr pr))

(cl-defmethod project-files ((pr (head my/projectile)) &optional _dirs)
  (let ((root (cdr pr)))
    (mapcar
     (lambda (file)
       (concat root file))
     (projectile-project-files root))))

(cl-defmethod project-ignores ((pr (head my/projectile)) _dir)
  (let ((default-directory (cdr pr)))
    (projectile-patterns-to-ignore)))

(with-eval-after-load 'project
  (add-to-list 'project-find-functions 'm/projectile-project-find-function)

cf. https://github.com/joaotavora/eglot/issues/697 <https://github.com/joaotavora/eglot/issues/697>
